9 add gini index to assesspy functions
ccao-data/assesspy pull request #10
Opened 2023-08-09 17:57 UTC by Damonamajor

First test to see if things come up when pulling.

Things of note:

2023-08-12 18:58 UTC, dfsnow requested changes

2023-08-12 18:58 UTC, dfsnow commented on requirements.txt
**suggestion (blocking):** It might be worth moving this entire package to using more modern packaging i.e. `pyproject.toml`. Then we could define optional dependencies for the vignette and tests separately from the actually requirements for the package (`numpy` only). [Here's an example package](https://github.com/r5py/r5py) using that technique.

That said, I'm not too familiar with best practices in the python packaging space. @wrridgeway and @jeancochrane, any thoughts here?

2023-08-14 13:55 UTC, wrridgeway commented on requirements.txt
I would prefer 1) spending some time to understand the implications for the entire package, 2) making this a separate issue and addressing it once this current issue is successfully merged.

2023-08-14 21:17 UTC, wrridgeway commented on assesspy/formulas.py
> +import pandas as pd
pandas was already a requirement for the package - it wasn't used in this script previously, but it _was_ used elsewhere, so i think we're okay here.

2023-08-15 14:34 UTC, dfsnow commented on assesspy/formulas.py
> +import pandas as pd
But it's used as a dependency for the vignette, not the package itself, no? I'll make another issue for updating to new package infra + factoring out pandas in the requirements (moving it to build dependencies).

2023-08-15 14:35 UTC, dfsnow commented on requirements.txt
Will make a separate issue!

2023-08-15 14:40 UTC, wrridgeway commented on assesspy/formulas.py
> +import pandas as pd
It's necessary for testing as well, but we can try our best to keep it out of formulas in the new issue.

2023-08-20 20:02 UTC, wrridgeway commented
@Damonamajor i'm getting a number of errors when I try to build docs for this branch:

![image](https://github.com/ccao-data/assesspy/assets/10358980/34ac839d-e2d7-421c-a14f-0e8306366539)

I think we split up mki_ki in formulas, but they aren't split in the documentation?

2023-08-23 18:54 UTC, wrridgeway approved these changes

2023-08-23 19:10 UTC, dfsnow approved these changes
Great job @Damonamajor and @wrridgeway. Excited to have this merged.

2023-08-23 19:10 UTC, merged